---
title: "Data_simulation_vasarely"
author: "Alexandra Banach 649005"
date: "4 Juli 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/limes/Documents/Semester6/Bachelorarbeit/vasarely/R")
library("vasarely")
```
Normal Marker, ten alleles
```{r}
letters <- c('A','B','C','D','E','F','G','H','I','J')
a1 <- sample(letters, 100, replace = TRUE)
a2 <- sample(letters, 100, replace = TRUE)
vasarely_data1 <- data.frame(a1,a2)
vasarely(vasarely_data1)
```
marker with null alleles
```{r}
a1 <- rep(letters, times=50)
a2 <- rep(letters, times=50)
a1 <- c(a1,sample(letters, 500, replace = TRUE))
a2 <- c(a2,sample(letters, 500, replace = TRUE))
vasarely_data2 <- data.frame(a1,a2)
vasarely(vasarely_data2)
```
Normal Marker, ten alleles, scaled
```{r}
vasarely(vasarely_data1, lower_color_value = 0, upper_color_value = 0.15)
```
AB-deficit (uncorrected): 25xAA, 10xAB, 20xBA, 55xBB
```{r}
a1 <- c(rep("A", each = 35), rep("B", each = 75))
a2 <- c(rep("A", each = 25), rep("B", each = 10),
        rep("A", each = 20), rep("B", each = 55))
vasarely_data3 <- data.frame(a1,a2)
vasarely(vasarely_data3)
```
AB-deficit(corrected): 25xAA, 25xAB, 20xBA, 40xBB
```{r}
a1 <- c(rep("A", each = 50), rep("B", each = 60))
a2 <- c(rep("A", each = 25), rep("B", each = 25),
        rep("A", each = 20), rep("B", each = 40))
vasarely_data4 <- data.frame(a1,a2)
vasarely(vasarely_data4)
```
marker D15S1012
```{r}
allele1 <- c(rep("A", each = 182), rep("B", each = 2), 
             rep("C", each = 189), rep("D", each = 40), rep("F", each = 28))
allele2 <- c(rep("A", each = 20), rep("C", each = 82), rep("D", each = 23),
             rep("E", each = 1), rep("F", each = 54), rep("G", each = 2),
             rep("C", each = 63), rep("D", each = 39), rep("E", each = 2),
             rep("F", each = 82), rep("G", each = 5), rep("D", each = 8),
             rep("F", each = 29), rep("G", each = 3), rep("F", each = 25),
             rep("G", each = 3))
marker_d15 <- data.frame(allele1, allele2)
vasarely(marker_d15)

```
marker D15S971
```{r}
allele_1 <- c(rep("A", each = 24), rep("B", each = 154), 
             rep("C", each = 9), rep("D", each = 26), 
             rep("E", each = 37), rep("F", each = 2))
allele_2 <- c(rep("B", each = 6), rep("C", each = 6), rep("D", each = 2),
             rep("E", each = 8), rep("F", each = 2), rep("B", each = 48),
             rep("C", each = 13), rep("D", each = 20), rep("E", each = 64),
             rep("F", each = 9), rep("D", each = 1), rep("E", each = 4),
             rep("F", each = 4), rep("D", each = 4), rep("E", each = 19),
             rep("F", each = 3), rep("E", each = 26), rep("F", each = 11), 
             rep("G", each =2))
marker <- data.frame(allele_1, allele_2)
vasarely(marker)
```
```{r}
vasarely(vasarely_data1)$statistic_values$p_value
```

